### ISSUE TITLE
Cannot find js-controller

### ISSUE THREAD

**Issue by hbrks** [Schnup89/ioBroker.openwrt#1]
**Describe the bug**  
crashed after start node main

**To Reproduce**  
[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node main.js`
Cannot find js-controller
[nodemon] app crashed - waiting for file changes before starting...

**Expected behavior**  
nodemon main

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
Node Details
*  node: v10.19.0
*  npm: 6.13.4
*  yarn: 1.16.0

**Additional context**

**Comment by Schnup89** [comment]
This package will only work within ioBroker as adapter.
Do you try to start this within ioBroker?
