### ISSUE TITLE
Start/stop interfaces?

### ISSUE THREAD

**Issue by raintonr** [Schnup89/ioBroker.openwrt#21]
Nice work with this adapter.

Useful for me, but... I'd like to be able to start/stop various interfaces from IoB and can't see how to achieve that. I've probably missed something or is this not possible?

**Comment by Schnup89** [comment]
closed

**Comment by raintonr** [comment]
Ah... erm... wait. I was going to implement this today but cannot find any "sendcommand" object. Where should it be in the object tree?

**Comment by Schnup89** [comment]
> Ah... erm... wait. I was going to implement this today but cannot find any "sendcommand" object. Where should it be in the object tree?

Just saw your message...
There are two Datapoints:
 
openwrt.0.sendCommand      <- Here you can write your command
openwrt.0.sendCommandLastResult   <- The result is written here
