### ISSUE TITLE
Driver don't work :(

### ISSUE THREAD

**Issue by 2scorpio** [Schnup89/ioBroker.openwrt#23]
Hello.
I started driver and have this error.
Whats i am doing wrong ?

Node.js v14.19.3
NPM 6.14.17

<html>
<body>

openwrt.0 | 2022-06-16 10:00:38.243 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
openwrt.0 | 2022-06-16 10:00:38.242 | info | terminating
openwrt.0 | 2022-06-16 10:00:38.242 | info | cleaned everything up...
openwrt.0 | 2022-06-16 10:00:38.239 | error | The id is empty! Please provide a valid id.
openwrt.0 | 2022-06-16 10:00:38.239 | error | Error: The id is empty! Please provide a valid id. at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19) at Openwrt.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3181:23) at /opt/iobroker/node_modules/iobroker.openwrt/main.js:128:22 at Array.forEach (<anonymous>) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.openwrt/main.js:127:25) at processImmediate (internal/timers.js:466:21)
openwrt.0 | 2022-06-16 10:00:38.237 | error | unhandled promise rejection: The id is empty! Please provide a valid id.
openwrt.0 | 2022-06-16 10:00:38.237 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
openwrt.0 | 2022-06-16 10:00:38.221 | debug | Saved new Token: c4739697dc465e2b61e72fd7a7303bf2
openwrt.0 | 2022-06-16 10:00:37.087 | debug | Called fHTTGetToken
openwrt.0 | 2022-06-16 10:00:37.087 | debug | ##### RUN ADAPTER #####
openwrt.0 | 2022-06-16 10:00:37.086 | debug | Decrypted the encrypted password!
openwrt.0 | 2022-06-16 10:00:37.021 | debug | ##### LOAD CONFIG #####
openwrt.0 | 2022-06-16 10:00:37.000 | info | starting. Version 0.0.2 (non-npm: Schnup89/ioBroker.openwrt#5bf9487c950d0a859f7a87da7978edac3b73a068) in /opt/iobroker/node_modules/iobroker.openwrt, node: v14.19.3, js-controller: 4.0.23

</body>
</html>

**Comment by Schnup89** [comment]
Hey [2scorpio](https://github.com/2scorpio),

please check that there is an alias set for every "ubus-command", if you dont need that, just delete the default one.
