### ISSUE TITLE
iobroker crash with version 0.0.3 - Investigation

### ISSUE THREAD

**Issue by Schnup89** [Schnup89/ioBroker.openwrt#26]
I see some issues with 0.0.3, dont update for now, I'll check this the next days

**Comment by Schnup89** [comment]
Updated repo to iobroker standards and implemented some error-checks.
Works fine for me now, please let me know if the adapter works for you in V0.0.3
###
Adapter wurde an den neuen iobroker Richtlinien angepasst und einige Fehlerüberprüfungen implementiert.
Sollte jemand den Adapter in der V0.0.3 installiert haben würde ich mich über eine kurze Rückmeldung freuen.

**Comment by 2scorpio** [comment]
don`t work :(

<html>
<body>


openwrt.0 | 2022-06-17 20:09:52.883 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
openwrt.0 | 2022-06-17 20:09:52.882 | info | terminating
openwrt.0 | 2022-06-17 20:09:52.881 | info | cleaned everything up...
openwrt.0 | 2022-06-17 20:09:52.877 | error | The id is empty! Please provide a valid id.
openwrt.0 | 2022-06-17 20:09:52.877 | error | Error: The id is empty! Please provide a valid id. at Utils.validateId (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/utils.js:114:19) at Openwrt.setObjectNotExists (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:3181:23) at /opt/iobroker/node_modules/iobroker.openwrt/main.js:128:22 at Array.forEach (<anonymous>) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.openwrt/main.js:127:25) at processImmediate (internal/timers.js:466:21)
openwrt.0 | 2022-06-17 20:09:52.875 | error | unhandled promise rejection: The id is empty! Please provide a valid id.
openwrt.0 | 2022-06-17 20:09:52.875 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
openwrt.0 | 2022-06-17 20:09:52.860 | debug | Saved new Token: a1b9ae2290f6d3674949ab04766393cd
openwrt.0 | 2022-06-17 20:09:52.702 | debug | Called fHTTGetToken
openwrt.0 | 2022-06-17 20:09:52.700 | debug | ##### RUN ADAPTER #####
openwrt.0 | 2022-06-17 20:09:52.699 | debug | Decrypted the encrypted password!
openwrt.0 | 2022-06-17 20:09:52.637 | debug | ##### LOAD CONFIG #####
openwrt.0 | 2022-06-17 20:09:52.615 | info | starting. Version 0.0.2 (non-npm: Schnup89/ioBroker.openwrt#5bf9487c950d0a859f7a87da7978edac3b73a068) in /opt/iobroker/node_modules/iobroker.openwrt, node: v14.19.3, js-controller: 4.0.23


</body>
</html>

**Comment by Schnup89** [comment]
Can you check the version in the instance-tab?

Log file shows Version 0.0.2

[]...starting. Version 0.0.2...[]

**Comment by 2scorpio** [comment]
sorry :)
i update version :)
driver start work, but i don't see any data :(
![image](https://user-images.githubusercontent.com/36969533/174354681-2a430efc-9d87-4446-b995-324dad884aac.png)

**Comment by Schnup89** [comment]
I think the adapter works, so I'm closing this.
@2scorpio If you have issues getting the data, please create a new issue.
